.Dd October 29, 2022
.Dt nanoid 3
.Sh NAME
.Nm nanoid
.Nd one line about what it does
.\" .Sh LIBRARY
.\" For sections 2, 3, and 9 only.
.\" Not used in OpenBSD.
.Sh SYNOPSIS
.Nm
.Op Fl options
.Ar
.Sh DESCRIPTION
The
.Nm
utility processes files ...
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh AUTHORS
Written by
.An Yana Luna-Terra Aq Mt yana@riseup.net .
