.Dd October 30, 2022
.Dt NANOIDGEN 1
.Sh NAME
.Nm nanoidgen
.Nd generate a Nano ID
.Sh SYNOPSIS
.Nm
.Op length
.Sh DESCRIPTION
.Nm
.Sh EXIT STATUS
Other than the standard success and failure exit codes, 64 means that
.Nm
there was an issue.
.Sh SEE ALSO
.Xr nanoid 3
.Sh AUTHORS
Written by
.An Yana Luna-Terra Aq Mt yana@yana.moe .
